kiegroup/run-tests-with-build

run-tests-with-build-kogito-runtimes/pom.xml

Rest of kogito-runtimes modules added.
archetypes repo is failing so put into excludes even though not included (for visibility). It needs investigation.

kogito-runtimes add rest of modules

---

run-tests-with-build-kogito-runtimes/pom.xml

See https://issues.redhat.com/browse/KOGITO-4425

KOGITO-4425: Adapt to project restructuralization

---

pom.xml
run-tests-with-build-optaplanner/README.md
run-tests-with-build-optaplanner/pom.xml
settings/settings.xml

Launch community tests for OptaPlanner
cc @michaltomco

Add community tests OptaPlanner

---

run-tests-with-build-optaplanner-optawebs/README.md
run-tests-with-build-optaplanner-optawebs/pom.xml

Added a parameter to specify container runtime
https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/dupliaka/job/run-tests-generated/

Propagate properties to maven invoked app

---

.gitignore
README.md
pom.xml
run-tests-with-build-kogito-apps/pom.xml
run-tests-with-build-kogito-examples/pom.xml
run-tests-with-build-kogito-runtimes/README.md
run-tests-with-build-kogito-runtimes/pom.xml
scripts/resolve-includes.groovy

Dynamic control over includes/excludes using groovy script.

introduce resolve-includes.groovy script

---

README.md
pom.xml
run-tests-with-build-kogito-decision-services-quickstarts-optawebs/pom.xml
run-tests-with-build-kogito-decision-services-quickstarts/pom.xml
run-tests-with-build-kogito-sources-optawebs/pom.xml
run-tests-with-build-kogito-sources/pom.xml
run-tests-with-build-optaplanner-optawebs-parent/pom.xml

Adding tests for sources.zip as provided in handover.
Intention is to have a job just for cr phase (when this bundle is available).

Add module to run build in sources zip.

---

run-tests-with-build-project-sources-dependency-get/pom.xml

As a follow-up on groupId change in https://github.com/kiegroup/kogito-examples/pull/693 .

Adapt to changed kogito-examples groupId

---

run-tests-with-build-optawebs-parent/README.md
run-tests-with-build-optawebs-parent/optawebs-project-sources-test/common.sh
run-tests-with-build-optawebs-parent/optawebs-project-sources-test/optaweb-employee-rostering-test-script-openshift.sh
run-tests-with-build-optawebs-parent/optawebs-project-sources-test/optaweb-vehicle-routing-test-script-openshift.sh
run-tests-with-build-optawebs-parent/optawebs-project-sources-test/pom.xml

Run optaweb projects ERP and VRP on OpenShift
https://qe-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/custom/job/adupliak/job/run-tests-vehhicle-routing-openshift/
https://qe-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/custom/job/adupliak/job/run-tests-employee-rostering-openshift/

Add openshift profile

---

run-tests-with-build-optawebs-parent/optawebs-project-sources-test/common.sh

I have removed exit 1 since instant exist in common.sh will skip the oc delete project

Do not exit on timeout

---

pom.xml
run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
scripts/resolve-includes.groovy

cherry-pick of #35 
* adapt kogito-runtimes modules after KOGITO-5712
* fix nexus prop resolution
* use install goal in kogito-runtimes-sources-zip-test

update kogito-runtimes modules after KOGITO-5712 (#35)

---

pom.xml
run-tests-with-build-kogito-editors-java/pom.xml

https://issues.redhat.com/browse/BAQE-1829

BAQE-1829: Implement test execution for kogito-editors-java repository

---

pom.xml
run-tests-with-build-kie-tools-stunner-editors/pom.xml

https://issues.redhat.com/browse/BAQE-2224

BAQE-2224: Rename kogito-tooling to kie-tools in QE test-suite

---

pom.xml
run-tests-with-build-kogito-examples-parent/README.md
run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
run-tests-with-build-kogito-examples-parent/kogito-examples-scm-checkout-test/pom.xml
run-tests-with-build-kogito-examples-parent/kogito-examples-sources-zip-test/pom.xml
run-tests-with-build-kogito-examples-parent/pom.xml
run-tests-with-build-kogito-runtimes-parent/README.md
run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/README.md
run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-scm-checkout-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-sources-zip-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/pom.xml
run-tests-with-build-scm-checkout/pom.xml
scripts/write-test-properties-file-for-invoker.groovy

Test type git clone 7.59.x

---

scripts/write-test-properties-file-for-invoker.groovy

Adding trim to handle possible whitespace in maven properties.

add trim to maven property parsing

---

run-tests-with-build-optawebs-parent/optawebs-project-sources-test/optaweb-employee-rostering-test-script-openshift.sh

Change sed option to avoid docker pull limits
Increase timeout to allow oc to request BE in slow environments

Increase timeout to allow oc to request BE in slow environments

---

run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-project-sources-test/pom.xml

See:
https://issues.redhat.com/browse/RHPAM-4256

Exclude native tests due to UnsupportedFeatureException

---

run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-project-sources-test/pom.xml

Cherry-pick of #65 
* Exclude native tests due to UnsupportedFeatureException
See:
https://issues.redhat.com/browse/RHPAM-4256

Exclude native tests due to UnsupportedFeatureException (#65)

---

run-tests-with-build-kogito-examples-parent/kogito-examples-sources-zip-test/pom.xml
run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
run-tests-with-build-optaplanner-parent/optaplanner-sources-zip-test/pom.xml
run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-sources-zip-test/pom.xml
run-tests-with-build-optawebs-parent/optawebs-sources-zip-test/pom.xml

kogito-runtimes|examples-sources-zip: Fix POM files location

---

pom.xml
run-tests-with-build-kogito-apps-parent/README.md
run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
run-tests-with-build-kogito-apps-parent/pom.xml
run-tests-with-build-project-sources-dependency-get/pom.xml

[serverless-logic-1.24.x] BAQE-2375 add kogito-apps parent

---

pom.xml
run-tests-with-build-kogito-apps-parent/README.md
run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
run-tests-with-build-kogito-apps-parent/pom.xml
run-tests-with-build-project-sources-dependency-get/pom.xml

Adding kogito-apps similarly to what we have for kogito-runtimes.

BAQE-2375 add kogito-apps parent

---

run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
run-tests-with-build-drools-parent/pom.xml

Test execution against [_BAQE-2203-add-unpack-build-maven-plugin_] branch: https://qe-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/drosa/job/test-seed/job/TESTING/job/1.24/job/KOGITO_RUNTIMES-CR/job/community/job/baseline/job/drools-baseline/4/consoleFull

[serverless-logic-1.24.x] BAQE 2203 - add unpack-build-maven-plugin

---

run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml

`maven.main.skip` in kogito-runtimes and kogito-apps projects-sources variants.

BAQE-2396 skip maven main compilation kogito-runtimes, kogito-apps

---

run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml

PR set:
* https://gitlab.cee.redhat.com/business-automation/qe-jenkins/-/merge_requests/782
* https://github.com/kiegroup/run-tests-with-build/pull/86

BAQE-2478 - Skip Data Index image build in kogito-apps

---

run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml

[9.100.x] SRVLOGIC-232: Introduce new images to test suites

---

run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml

SRVLOGIC-232: Introduce new images to test suites

---

run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml

Fix missing commit on prod branch

[srvlogic-9.100.x] SRVLOGIC-232: Introduce new images to test suites

---

run-tests-with-build-drools/pom.xml

Jira: https://issues.redhat.com/browse/BAQE-3125

[BAQE-3125] Disable failing Drools kie-ci tests
