- run-tests-with-build-kogito-runtimes/pom.xml
Enabling the test in subject, it was previously failing due to no docker on the CI instance.
Verified in build no. 16.
> kogito-runtimes - enable integration-tests-quarkus-processes

- pom.xml
- run-tests-with-build-kogito-decision-services-quickstarts-optawebs/README.md
- run-tests-with-build-kogito-decision-services-quickstarts-optawebs/pom.xml
- run-tests-with-build-kogito-decision-services-quickstarts/README.md
- run-tests-with-build-kogito-decision-services-quickstarts/pom.xml
- run-tests-with-build-optaplanner-optawebs-parent/pom.xml
- run-tests-with-build-optaplanner-optawebs/pom.xml
The added kogito-decision-services-quickstarts module should be used for testing submodules:
- kogito-examples
- optaplanner-quickstarts
The added kogito-decision-services-quickstarts-optawebs module should be used for testing submodules:
- optaweb-vehidle-routing
- optaweb-employee-rostering
> decision-services-quickstarts module

- run-tests-with-build-optawebs-parent/README.md
- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/common.sh
- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/optaweb-employee-rostering-test-script-openshift.sh
- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/optaweb-vehicle-routing-test-script-openshift.sh
- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/pom.xml
- run-tests-with-build-optawebs-parent/pom.xml
Fail fast if the back end is not reachable after deployment
Pull images by digest to avoid docker limits - by using mirrors
Add container engine configuration
Add skip test parameter to property of the parent invoker (in other case it gets overwritten)
> Incorporate fixes for optawebs stability

- run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
Enable to build quarkus examples in native mode.
* Still execute just `productized` examples - can't combine `productized` and `native` profiles, cause it would mix in also springboot modules from `productized` profile and bring in also other non-productized modules.
* Allow overriding mandrel builder image to be used.
> [kogito-examples] add native build option

- pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
- scripts/resolve-includes.groovy
* Remove explicit execution of integration-tests (those are now part of `productized` profile, so are included out of the box).
* Fix settings.xml handling - passing `${session.request.userSettingsFile.path}` to invoker through `settingsFile` causes issues due to non-expanded system properties (nexus.group, nexus.host, etc). Reason is that by default system properties are not passed from parent maven build to invoker, thus are not available. Retracting from this approach, invoker by default uses `${settings}` value imported, which means that invoker shares what is passed to maven build via `-s`. This is enough in our case and no explicit passing of settingsFile is needed at all. (Applies just to maven-invoker-plugin, any other means of running mvn builds might require using the …
> update kogito-runtimes modules after KOGITO-5712

- config-files/invoker.properties
The fail-never policy hides build failures in case of missing deps, etc.
> use fail-at-end invoker.failureBehavior

- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/pom.xml
Cypress test belongs to the community optaweb
The cypress version which get used there changed
The scritpt that launches cypress tests on openshift runs it with shell adding another profile in optaweb community will pollute the pom's simplicity
> Update cypress version for openshift integration tests

- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/pom.xml
Cypress test belongs to the community optaweb
The cypress version which get used there changed
The script that launches cypress tests on openshift runs it with shell adding another profile in optaweb community will pollute the pom's simplicity
The changes from main
https://github.com/kiegroup/run-tests-with-build/pull/42
> Update cypress version for openshift integration tests 

- pom.xml
The command `grep -ri kogito.examples.repo.url` returns single occurence, this I think we can remove this property. I spotted this during https://github.com/kiegroup/run-tests-with-build/pull/44/files review, where similar property was introduced `kogito.editors.java.repo.url`. So I wanted to check consistency we use similar property in simalr way, but found out we do not use that property at all.
> Remove unused property kogito.examples.repo.url

- pom.xml
- run-tests-with-build-kogito-tooling-stunner-editors/pom.xml
Now it invokes the same teste, but from kogito-tooling repository
stunner-editors package.
> BAQE-2212 Update kogito-editors-java tests execution after migration

- run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
- run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-project-sources-test/pom.xml
- run-tests-with-build-optawebs-parent/optawebs-project-sources-test/pom.xml
Quickstarts are collected in different places of the artifact repository since the pojects are completely undependent I decide to get rid of filtering. Also I added non-native so to not append pomincludes together in case of poms located in different folders
Optaplanner profiles is just the same as in kogito.
> Add native for quickstarts and optaplanner quarkus integration

- run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
optaplanner-parent has docs folder that contains ascidoctor files which we skip in this certification if skip filtering it will not be able to deliver index.pdf which we need while building uberjar
> Return filtering to avoid testing full profile

- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-project-sources-test/pom.xml
quarkus.native.native-image-xmx - the maximum Java heap to be used during the native image generation
To build native images it should be at least 8 Gb memory given for OptaPlanner projects
> Add quarkus.native.native-image-xmx

- pom.xml
- run-tests-with-build-kogito-examples-parent/README.md
- run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
- run-tests-with-build-kogito-examples-parent/kogito-examples-scm-checkout-test/pom.xml
- run-tests-with-build-kogito-examples-parent/kogito-examples-sources-zip-test/pom.xml
- run-tests-with-build-kogito-examples-parent/pom.xml
- run-tests-with-build-kogito-runtimes-parent/README.md
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/README.md
- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-scm-checkout-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-sources-zip-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/pom.xml
- run-tests-with-build-scm-checkout/pom.xml
- scripts/write-test-properties-file-for-invoker.groovy
There are two commits:
1. Adding support for scm-checkout test.type, which allows cloning tests directly from branch.
a. This is applicable in cases where projects themselves allow for version overrides, like for BOMs in kogito-examples and optaplanner-quickstarts.
2. Adding support for passing system properties through invoker.
a. Groovy script to get properties not defined in pom.xml into test.properties (passed to overall run-tests-with-build using `-Dkogito.bom.group-id` for example).
b. Test properties file is placed next to each pom.xml file inside the sources directory (recursively).
c. The behavior is pluggable, by default turned off, requires plugin entry inside module's build section.
> Quarkus platform testing changes

- run-tests-with-build-kogito-examples-parent/kogito-examples-project-sources-test/pom.xml
- run-tests-with-build-kogito-examples-parent/kogito-examples-scm-checkout-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-scm-checkout-test/pom.xml
Adding property quarkus-plugin.version as a possible override for kogito-runtimes, kogito-examples and  optaplanner-quickstarts.
> enable quarkus-plugin.version property override

- run-tests-with-build-kogito-examples-parent/kogito-examples-sources-zip-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
- run-tests-with-build-optaplanner-parent/optaplanner-sources-zip-test/pom.xml
- run-tests-with-build-optaplanner-quickstarts-parent/optaplanner-quickstarts-sources-zip-test/pom.xml
- run-tests-with-build-optawebs-parent/optawebs-sources-zip-test/pom.xml
The structure of the sources zip is:
* openshift-serverless-logic-\<version\>-src
* org.kie.kogito-kogito-runtimes-\<version\>
* and so on
Changes already tested on pipelines.
> [serverless-logic-1.24.x] kogito-runtimes|examples-sources-zip: Fix POM files location

- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
- run-tests-with-build-drools-parent/pom.xml
Backporting BAQE-2203 [1] changes to main branch.
[1] https://github.com/kiegroup/run-tests-with-build/pull/76
> [main] BAQE 2203 - add unpack-build-maven-plugin

- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
Replace hard-coded 1.0-SNAPSHOT version by the property unpack.build.version.
> [serverless-logic-1.24.x] BAQE 2203 - add unpack-build-maven-plugin fix unpack.build.version property

- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
backport: https://github.com/kiegroup/run-tests-with-build/pull/82
> Added data-index image to runtimes props

- pom.xml
- run-tests-with-build-drools-parent/README.md
- run-tests-with-build-drools-parent/drools-local-repo-test/pom.xml
- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
- run-tests-with-build-drools-parent/pom.xml
- run-tests-with-build-kogito-apps-parent/README.md
- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/pom.xml
- run-tests-with-build-kogito-examples-parent/README.md
- run-tests-with-build-kogito-examples-parent/kogito-examples-local-repo-test/pom.xml
- run-tests-with-build-kogito-examples-parent/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-local-repo-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/pom.xml
- scripts/resolve-includes.groovy
Adding option to invoke tests on local directory.
* Adding `test.type=local-repo`
* Adding property `sources.directory.local.repo`
* Checked for non-empty value
* Checked for existing path
* Removing incorrect sources-zip test.type for drools (was not implemented, but there were some traces)
* Adding readme for drools-parent.
> Add local-repo test.type

- scripts/resolve-includes.groovy
InvocationTargetException: No signature of method: static java.nio.file.Path.of() is applicable for argument types: (File, String) :wink:
> resolve-includes.groovy: Fix Path.of() signature

- pom.xml
- run-tests-with-build-drools-parent/drools-local-repo-test/pom.xml
- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-local-repo-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
- run-tests-with-build-optaplanner-parent/optaplanner-project-sources-test/pom.xml
Parameterizing the final (last) invoker plugin goal.
Use case - sometimes it's enough to run `test` on a project, other times `integration-test` or `verify`.
In root pom.xml
* Introducing `invoker.goal` property with default value `verify` and using where goal `verify` used to be.
* Introducing explicit properties for used goals, e.g. `invoker.goal.verify`, `invoker.goal.test`.
* Setting `${invoker.goal}` value to the pluginManagement default configuration.
In children's pom.xml:
* Use property `${invoker.goal}` for the last goal in invoker plugin execution.
In some of child pom.xml:
* Override `invoker.goal` with a different goal, e.g. `${invoker.goal.install}`
* This keeps things in sync when overriding using `-Dinvoker.goal`, the other option, directly using `${invoker.goal.install}` …
> [kie-issues#274] parameterize final invoker goal

- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-local-repo-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
As tests have been moved to the kogito-apps, we should also move the overriding property.
> KOGITO-9523 - Move Data Index DevService test to kogito-apps

- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
Remove unused mongodb and infinispan container images 
Add postgresql image for data index common job service image 
Fix previous mistakenlused labels
> [srvlogic-9.100.x] BAQE-2898: Fix kogito-apps baseline not using correct images for testing

- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
Remove unused mongodb and infinispan container images 
Add postgresql image for data index common job service image
Fix previous mistakenlused labels
> BAQE-2898: Fix kogito-apps baseline not using correct images for testing

- run-tests-with-build-kogito-apps-parent/kogito-apps-local-repo-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-project-sources-test/pom.xml
- run-tests-with-build-kogito-apps-parent/kogito-apps-sources-zip-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-local-repo-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-project-sources-test/pom.xml
- run-tests-with-build-kogito-runtimes-parent/kogito-runtimes-sources-zip-test/pom.xml
Allow this for to deal with compilation fails. Temporary workaround.
> [srvlogic-9.100.x] BAQE-2903: Workarund, allow checkstyle.skip control

- run-tests-with-build-drools/pom.xml
Jira: [BAQE-3125](https://issues.redhat.com/browse/BAQE-3125)
Backported from https://github.com/kiegroup/run-tests-with-build/pull/110
> [9.103.x][BAQE-3125] Disable failing Drools kie-ci tests 

- run-tests-with-build-drools/pom.xml
Jira: [BAQE-3125](https://issues.redhat.com/browse/BAQE-3125)
Backported from https://github.com/kiegroup/run-tests-with-build/pull/110
> [9.102.x][BAQE-3125] Disable failing Drools kie-ci tests (#110)

- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
Jira: [BAQE-3125](https://issues.redhat.com/browse/BAQE-3125)
Backported from https://github.com/kiegroup/run-tests-with-build/pull/114
> [9.102.x][BAQE-3125] Exclude also drools-project-sources-test

- run-tests-with-build-drools-parent/drools-project-sources-test/pom.xml
Jira: [BAQE-3125](https://issues.redhat.com/browse/BAQE-3125)
Backported from https://github.com/kiegroup/run-tests-with-build/pull/114
> [9.103.x][BAQE-3125] Exclude also drools-project-sources-test
